
export const TITLE_DATA = [
    "AI Engineer",
    "Actuary",
    "Analyst",
    "Architect",
    "Art Director",
    "Assistant Manager",
    "Associate Director",
    "Associate Engineer",
    "Automation Engineer",
    "Biotechnology Associate",
    "Brand Manager",
    "Branch Manager",
    "Business Development",
    "CFD Engineer",
    "Cloud Engineer",
    "Computer Vision Engineer",
    "Content Writer",
    "Copywriter",
    "Creative Director",
    "Cybersecurity Analyst",
    "Data Analyst",
    "Data Engineer",
    "Data Scientist",
    "Database Administrator",
    "Design Engineer",
    "DevOps Engineer",
    "DevSecOps Engineer",
    "Digital Marketing",
    "Director of Engineering",
    "Director of Marketing",
    "Engineer",
    "Engineering Director",
    "Executive Assistant",
    "Fashion Designer",
    "Field Service Engineer",
    "Finance Director",
    "Financial Analyst",
    "Front End Developer",
    "Full Stack Developer",
    "Game Developer",
    "Graphic Designer",
    "HR Executive",
    "Intern",
    "Java Developer",
    "Junior Architect",
    "Legal",
    "Machine Learning Engineer",
    "Manager",
    "Marketing Manager",
    "Mechanical Engineer",
    "Mobile App Developer",
    "Network Administrator",
    "Operations Manager",
    "Photographer",
    "Pipeline Engineer",
    "Principal Engineer",
    "Product Designer",
    "Project Manager",
    "Python Developer",
    "QA Engineer",
    "Research Assistant",
    "Sales Executive",
    "Sales Manager",
    "Senior Engineer",
    "Site Engineer",
    "Social Media Manager",
    "Software Developer",
    "Software Engineer",
    "Software Tester",
    "Supply Chain Analyst",
    "Talent Acquisition Specialist",
    "Technical Support",
    "UI/UX Designer",
    "Video Editor",
    "Web Developer",
    "Windows Administrator"
]



export const LOCATION_DATA = [
    "Agasthiswaram",
    "Ahmedabad",
    "Alwar",
    "Andhra Pradesh",
    "Bagalur",
    "Bangalore",
    "Bengaluru",
    "Bhubaneswar",
    "Bokaro",
    "Calcutta",
    "Chandigarh",
    "Chennai",
    "Chorasi",
    "Coimbatore",
    "Dahej",
    "Delhi",
    "Dombivli",
    "Faridabad",
    "Goa",
    "Goregaon",
    "Greater Bengaluru Area",
    "Greater Chennai Area",
    "Greater Delhi Area",
    "Greater Kolkata Area",
    "Gurgaon",
    "Gurugram",
    "Guwahati",
    "Hadapsar",
    "HSR Layout",
    "Hyderabad",
    "India",
    "Indore",
    "Itanagar",
    "Jaipur",
    "Jamnagar",
    "Kalamnuri",
    "Kanwali",
    "Karnataka",
    "Kharadi",
    "Kochi",
    "Kolkata",
    "Kottayam",
    "Madurai",
    "Mahad",
    "Maldah",
    "Marine Drive",
    "Mathura",
    "Mohali",
    "Mumbai",
    "Mumbai Metropolitan Region",
    "Nashik",
    "Navi Mumbai",
    "New Delhi",
    "New Town",
    "Noida",
    "Palghar",
    "Panvel",
    "Patia",
    "Pimpri-Chinchwad",
    "Pune",
    "Remote",
    "Sadar",
    "Serilingampalli",
    "Shivajinagar",
    "Sonipat",
    "Tamil Nadu",
    "Telangana",
    "Thiruvananthapuram",
    "Tiruchchirappalli",
    "Uttar Pradesh",
    "Vadodara",
    "Vagator",
    "Vaishali Nagar",
    "West Bengal",
    "Yerwada"
]
